### ISSUE TITLE
[BUG] False warning "variable 'xyz 'not defined"

### ISSUE THREAD

**Issue by NeutraleNull** [SQFvm/language-server#4]
**Describe the bug**
At the moment global variables are all marked as not defined. Eventhough it get assigned a value in the same line.

**To Reproduce**
1. Create new sqf or sqc (here only the transcripted file)
2. assign a value to a global variable e.g. ```globalVar = 1337;```
3. variable gets marked as not defined

**Expected behavior**
As soon a variable gets assigned a value it cannot be not defined.

**Additional context**
It really is annyoing because it generates a lot of warnings. In my little project over 100 at the moment. It hides real problems.

**Comment by severgun** [comment]
Very annoying. False alarms mask real one.
Also I think this false alarms cause server crash at big projects due to issues count.

**Comment by X39** [comment]
I am aware of the issue and the fix is to rewrite the language server. However, I currently do not have any minute to spare for this project and hence cannot work on it.


As nobody else picked it up, this pretty much means that for now the project is stale.

I may be able to continue working on the language server next year, but I do not want to make any promises regarding that.

**Comment by X39** [comment]
Solved in rewrite. See preview version.
